use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use serde_json::{Map, Value};

use crate::openapi_export;

const DEFAULT_OUTPUT: &str = "frontend/generated";

#[derive(Debug, Clone)]
struct Param {
    name: String,
    ts_name: String,
    location: String,
    required: bool,
    ty: String,
}

#[derive(Debug, Clone)]
struct Operation {
    group: String,
    method_name: String,
    params_type: Option<String>,
    http_method: String,
    path: String,
    path_params: Vec<Param>,
    query_params: Vec<Param>,
    body_type: Option<String>,
    return_type: String,
}

fn fail(message: impl std::fmt::Display) -> ! {
    eprintln!("❌ {}", message);
    std::process::exit(1);
}

pub fn run(language: &str, output: Option<&str>) {
    if language != "typescript" {
        fail(format!(
            "Unsupported client target '{}'. Currently supported: typescript.",
            language
        ));
    }

    let json = openapi_export::generate_json().unwrap_or_else(|e| fail(e));
    let spec: Value = serde_json::from_str(&json)
        .unwrap_or_else(|e| fail(format!("Failed to parse OpenAPI JSON: {}", e)));

    let output_dir = Path::new(output.unwrap_or(DEFAULT_OUTPUT));
    fs::create_dir_all(output_dir)
        .unwrap_or_else(|e| fail(format!("Failed to create {}: {}", output_dir.display(), e)));

    fs::write(output_dir.join("types.ts"), generate_types(&spec))
        .unwrap_or_else(|e| fail(format!("Failed to write types.ts: {}", e)));
    fs::write(output_dir.join("client.ts"), generate_client(&spec))
        .unwrap_or_else(|e| fail(format!("Failed to write client.ts: {}", e)));
    fs::write(
        output_dir.join("index.ts"),
        "export * from \"./types\";\nexport * from \"./client\";\n",
    )
    .unwrap_or_else(|e| fail(format!("Failed to write index.ts: {}", e)));

    println!("🧩 Wrote TypeScript client to {}", output_dir.display());
}

fn generate_types(spec: &Value) -> String {
    let mut out =
        String::from("// Generated by rustwing g client typescript. Do not edit manually.\n\n");
    let Some(schemas) = spec
        .pointer("/components/schemas")
        .and_then(Value::as_object)
    else {
        out.push_str("export type EmptyObject = Record<string, never>;\n");
        return out;
    };

    for (name, schema) in schemas {
        let type_name = sanitize_type_name(name);
        if let Some(props) = schema.get("properties").and_then(Value::as_object) {
            let required = required_set(schema);
            out.push_str(&format!("export interface {} {{\n", type_name));
            for (prop_name, prop_schema) in props {
                let optional = if required.contains(prop_name) {
                    ""
                } else {
                    "?"
                };
                out.push_str(&format!(
                    "  {}{}: {};\n",
                    quote_property(prop_name),
                    optional,
                    schema_to_ts(prop_schema, false)
                ));
            }
            out.push_str("}\n\n");
        } else {
            out.push_str(&format!(
                "export type {} = {};\n\n",
                type_name,
                schema_to_ts(schema, false)
            ));
        }
    }

    out
}

fn generate_client(spec: &Value) -> String {
    let operations = collect_operations(spec);
    let mut groups: BTreeMap<String, Vec<Operation>> = BTreeMap::new();
    for operation in operations {
        groups
            .entry(operation.group.clone())
            .or_default()
            .push(operation);
    }

    let mut out = String::from(
        r#"// Generated by rustwing g client typescript. Do not edit manually.
import type * as Types from "./types";

export interface RustwingClientOptions {
  baseUrl: string;
  getToken?: () => string | null | undefined | Promise<string | null | undefined>;
  fetch?: typeof fetch;
}

export class RustwingRequestError extends Error {
  constructor(
    public status: number,
    public payload: unknown,
  ) {
    super(`Rustwing request failed with status ${status}`);
  }
}

type QueryValue = string | number | boolean | null | undefined;

interface RequestOptions {
  method: string;
  path: string;
  query?: Record<string, QueryValue>;
  body?: unknown;
}

"#,
    );

    for operations in groups.values() {
        for op in operations {
            if let Some(params_type) = &op.params_type {
                out.push_str(&format!("export interface {} {{\n", params_type));
                for param in op.path_params.iter().chain(op.query_params.iter()) {
                    let optional = if param.required { "" } else { "?" };
                    out.push_str(&format!("  {}{}: {};\n", param.ts_name, optional, param.ty));
                }
                if let Some(body_type) = &op.body_type {
                    out.push_str(&format!("  body: {};\n", body_type));
                }
                out.push_str("}\n\n");
            }
        }
    }

    out.push_str("export function createRustwingClient(options: RustwingClientOptions) {\n");
    out.push_str("  const request = createRequest(options);\n\n");
    out.push_str("  return {\n");

    for (group, operations) in &groups {
        out.push_str(&format!("    {}: {{\n", group));
        for op in operations {
            let params_required = op.params_type.as_ref().is_some_and(|_| {
                op.body_type.is_some() || op.path_params.iter().any(|p| p.required)
            });
            let params_sig = match &op.params_type {
                Some(params_type) if params_required => format!("params: {}", params_type),
                Some(params_type) => format!("params: {} = {{}}", params_type),
                None => String::new(),
            };
            let params_ref = if op.params_type.is_some() {
                "params"
            } else {
                "undefined"
            };
            let path_expr = if op.path_params.is_empty() {
                format!("\"{}\"", op.path)
            } else {
                format!("buildPath(\"{}\", {})", op.path, params_ref)
            };
            let query_expr = if op.query_params.is_empty() {
                String::new()
            } else {
                let names = op
                    .query_params
                    .iter()
                    .map(|param| format!("\"{}\"", param.name))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!(", query: pickQuery({}, [{}])", params_ref, names)
            };
            let body_expr = if op.body_type.is_some() {
                format!(", body: {}.body", params_ref)
            } else {
                String::new()
            };
            out.push_str(&format!(
                "      {}: ({}) => request<{}>({{ method: \"{}\", path: {}{}{} }}),\n",
                op.method_name,
                params_sig,
                op.return_type,
                op.http_method,
                path_expr,
                query_expr,
                body_expr
            ));
        }
        out.push_str("    },\n");
    }

    out.push_str("  };\n");
    out.push_str("}\n\n");
    out.push_str(
        r#"function createRequest(options: RustwingClientOptions) {
  const fetchImpl = options.fetch ?? fetch;
  const baseUrl = options.baseUrl.replace(/\/$/, "");

  return async function request<T>(requestOptions: RequestOptions): Promise<T> {
    const url = new URL(requestOptions.path, `${baseUrl}/`);
    for (const [key, value] of Object.entries(requestOptions.query ?? {})) {
      if (value !== undefined && value !== null) {
        url.searchParams.set(key, String(value));
      }
    }

    const headers: Record<string, string> = {
      Accept: "application/json",
    };

    let body: string | undefined;
    if (requestOptions.body !== undefined) {
      headers["Content-Type"] = "application/json";
      body = JSON.stringify(requestOptions.body);
    }

    const token = await options.getToken?.();
    if (token) {
      headers.Authorization = `Bearer ${token}`;
    }

    const response = await fetchImpl(url, {
      method: requestOptions.method,
      headers,
      body,
    });

    if (!response.ok) {
      throw new RustwingRequestError(response.status, await readPayload(response));
    }

    if (response.status === 204) {
      return undefined as T;
    }

    return (await readPayload(response)) as T;
  };
}

async function readPayload(response: Response): Promise<unknown> {
  const text = await response.text();
  if (!text) {
    return undefined;
  }

  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

function buildPath(template: string, params: unknown): string {
  const values = (params ?? {}) as Record<string, unknown>;
  return template.replace(/\{([^}]+)\}/g, (_match, key: string) => {
    const value = values[toCamelCase(key)] ?? values[key];
    if (value === undefined || value === null) {
      throw new Error(`Missing path parameter: ${key}`);
    }
    return encodeURIComponent(String(value));
  });
}

function pickQuery(params: unknown, names: string[]): Record<string, QueryValue> {
  const values = (params ?? {}) as Record<string, QueryValue>;
  const query: Record<string, QueryValue> = {};
  for (const name of names) {
    query[name] = values[toCamelCase(name)] ?? values[name];
  }
  return query;
}

function toCamelCase(value: string): string {
  return value.replace(/_([a-zA-Z0-9])/g, (_match, part: string) => part.toUpperCase());
}
"#,
    );

    out
}

fn collect_operations(spec: &Value) -> Vec<Operation> {
    let mut operations = Vec::new();
    let Some(paths) = spec.get("paths").and_then(Value::as_object) else {
        return operations;
    };

    let mut method_counts: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();

    for (path, path_item) in paths {
        let Some(path_item) = path_item.as_object() else {
            continue;
        };

        for method in ["get", "post", "patch", "put", "delete"] {
            let Some(operation) = path_item.get(method).and_then(Value::as_object) else {
                continue;
            };

            let group = operation
                .get("tags")
                .and_then(Value::as_array)
                .and_then(|tags| tags.first())
                .and_then(Value::as_str)
                .map(group_name)
                .unwrap_or_else(|| "default".to_string());
            let mut method_name = infer_method_name(method, path, operation);
            let used = method_counts.entry(group.clone()).or_default();
            if used.contains(&method_name) {
                let fallback =
                    operation_id(operation).unwrap_or_else(|| format!("{}_{}", method, path));
                method_name = lower_camel(&fallback);
            }
            used.insert(method_name.clone());

            let params = collect_params(operation);
            let path_params = params
                .iter()
                .filter(|param| param.location == "path")
                .cloned()
                .collect::<Vec<_>>();
            let query_params = params
                .iter()
                .filter(|param| param.location == "query")
                .cloned()
                .collect::<Vec<_>>();
            let body_type = request_body_type(operation);
            let return_type = response_type(operation);
            let params_type =
                if path_params.is_empty() && query_params.is_empty() && body_type.is_none() {
                    None
                } else {
                    Some(format!(
                        "{}{}Params",
                        pascal_case(&method_name),
                        pascal_case(&group)
                    ))
                };

            operations.push(Operation {
                group,
                method_name,
                params_type,
                http_method: method.to_uppercase(),
                path: path.to_string(),
                path_params,
                query_params,
                body_type,
                return_type,
            });
        }
    }

    operations
}

fn collect_params(operation: &Map<String, Value>) -> Vec<Param> {
    operation
        .get("parameters")
        .and_then(Value::as_array)
        .map(|params| {
            params
                .iter()
                .filter_map(|param| {
                    let name = param.get("name")?.as_str()?.to_string();
                    let location = param.get("in")?.as_str()?.to_string();
                    let required = param
                        .get("required")
                        .and_then(Value::as_bool)
                        .unwrap_or(false)
                        || location == "path";
                    let ty = param
                        .get("schema")
                        .map(|schema| schema_to_ts(schema, true))
                        .unwrap_or_else(|| "unknown".to_string());
                    Some(Param {
                        ts_name: lower_camel(&name),
                        name,
                        location,
                        required,
                        ty,
                    })
                })
                .collect()
        })
        .unwrap_or_default()
}

fn request_body_type(operation: &Map<String, Value>) -> Option<String> {
    let schema = operation
        .get("requestBody")?
        .get("content")?
        .get("application/json")?
        .get("schema")?;
    Some(schema_to_ts(schema, true))
}

fn response_type(operation: &Map<String, Value>) -> String {
    let Some(responses) = operation.get("responses").and_then(Value::as_object) else {
        return "void".to_string();
    };

    for code in ["200", "201", "202", "204"] {
        if let Some(response) = responses.get(code) {
            if code == "204" {
                return "void".to_string();
            }
            if let Some(schema) = response
                .get("content")
                .and_then(|content| content.get("application/json"))
                .and_then(|json| json.get("schema"))
            {
                return schema_to_ts(schema, true);
            }
        }
    }

    "void".to_string()
}

fn schema_to_ts(schema: &Value, qualified: bool) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        let name = reference.rsplit('/').next().unwrap_or(reference);
        let name = sanitize_type_name(name);
        return if qualified {
            format!("Types.{}", name)
        } else {
            name
        };
    }

    if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        let variants = values
            .iter()
            .filter_map(Value::as_str)
            .map(|value| format!("\"{}\"", value.replace('"', "\\\"")))
            .collect::<Vec<_>>();
        if !variants.is_empty() {
            return variants.join(" | ");
        }
    }

    for key in ["oneOf", "anyOf"] {
        if let Some(values) = schema.get(key).and_then(Value::as_array) {
            let parts = values
                .iter()
                .map(|schema| schema_to_ts(schema, qualified))
                .collect::<Vec<_>>();
            if !parts.is_empty() {
                return parts.join(" | ");
            }
        }
    }

    if let Some(values) = schema.get("allOf").and_then(Value::as_array) {
        let parts = values
            .iter()
            .map(|schema| schema_to_ts(schema, qualified))
            .collect::<Vec<_>>();
        if !parts.is_empty() {
            return parts.join(" & ");
        }
    }

    let mut nullable = schema
        .get("nullable")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    let ty = schema.get("type");
    let base = if let Some(types) = ty.and_then(Value::as_array) {
        let parts = types
            .iter()
            .filter_map(Value::as_str)
            .filter_map(|ty| {
                if ty == "null" {
                    nullable = true;
                    None
                } else {
                    Some(type_name_to_ts(ty, schema, qualified))
                }
            })
            .collect::<Vec<_>>();
        if parts.is_empty() {
            "unknown".to_string()
        } else {
            parts.join(" | ")
        }
    } else if let Some(ty) = ty.and_then(Value::as_str) {
        type_name_to_ts(ty, schema, qualified)
    } else if schema.get("properties").is_some() {
        object_to_ts(schema, qualified)
    } else {
        "unknown".to_string()
    };

    if nullable && base != "null" {
        format!("{} | null", base)
    } else {
        base
    }
}

fn type_name_to_ts(ty: &str, schema: &Value, qualified: bool) -> String {
    match ty {
        "string" => "string".to_string(),
        "integer" | "number" => "number".to_string(),
        "boolean" => "boolean".to_string(),
        "array" => {
            let item_type = schema
                .get("items")
                .map(|items| schema_to_ts(items, qualified))
                .unwrap_or_else(|| "unknown".to_string());
            format!("{}[]", item_type)
        }
        "object" => object_to_ts(schema, qualified),
        "null" => "null".to_string(),
        _ => "unknown".to_string(),
    }
}

fn object_to_ts(schema: &Value, qualified: bool) -> String {
    if let Some(props) = schema.get("properties").and_then(Value::as_object) {
        let required = required_set(schema);
        let fields = props
            .iter()
            .map(|(name, schema)| {
                let optional = if required.contains(name) { "" } else { "?" };
                format!(
                    "{}{}: {}",
                    quote_property(name),
                    optional,
                    schema_to_ts(schema, qualified)
                )
            })
            .collect::<Vec<_>>()
            .join("; ");
        return format!("{{ {} }}", fields);
    }

    if let Some(additional) = schema.get("additionalProperties") {
        if additional == &Value::Bool(true) {
            return "Record<string, unknown>".to_string();
        }
        return format!("Record<string, {}>", schema_to_ts(additional, qualified));
    }

    "Record<string, unknown>".to_string()
}

fn required_set(schema: &Value) -> BTreeSet<String> {
    schema
        .get("required")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(Value::as_str)
                .map(ToOwned::to_owned)
                .collect()
        })
        .unwrap_or_default()
}

fn operation_id(operation: &Map<String, Value>) -> Option<String> {
    operation
        .get("operationId")
        .and_then(Value::as_str)
        .map(ToOwned::to_owned)
}

fn infer_method_name(method: &str, path: &str, operation: &Map<String, Value>) -> String {
    if let Some(operation_id) = operation_id(operation) {
        let lower = lower_camel(&operation_id);
        if matches!(lower.as_str(), "register" | "login" | "health") {
            return lower;
        }
    }

    if method == "get" && path.ends_with("/cursor") {
        "listCursor".to_string()
    } else if method == "get"
        && path
            .rsplit('/')
            .next()
            .is_some_and(|part| part.starts_with('{'))
    {
        "get".to_string()
    } else if method == "get" {
        "list".to_string()
    } else if method == "post" {
        "create".to_string()
    } else if method == "patch" || method == "put" {
        "update".to_string()
    } else if method == "delete" {
        "delete".to_string()
    } else {
        lower_camel(method)
    }
}

fn group_name(tag: &str) -> String {
    lower_camel(tag)
}

fn sanitize_type_name(name: &str) -> String {
    pascal_case(name)
}

fn pascal_case(value: &str) -> String {
    words(value)
        .into_iter()
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<String>()
}

fn lower_camel(value: &str) -> String {
    let pascal = pascal_case(value);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

fn words(value: &str) -> Vec<String> {
    let mut words = Vec::new();
    let mut current = String::new();
    let mut previous_was_lower_or_digit = false;

    for ch in value.chars() {
        if !ch.is_ascii_alphanumeric() {
            if !current.is_empty() {
                words.push(std::mem::take(&mut current));
            }
            previous_was_lower_or_digit = false;
            continue;
        }

        if ch.is_ascii_uppercase() && !current.is_empty() && previous_was_lower_or_digit {
            words.push(std::mem::take(&mut current));
        }

        current.push(ch.to_ascii_lowercase());
        previous_was_lower_or_digit = ch.is_ascii_lowercase() || ch.is_ascii_digit();
    }

    if !current.is_empty() {
        words.push(current);
    }

    words
}

fn quote_property(name: &str) -> String {
    if is_identifier(name) {
        name.to_string()
    } else {
        format!("\"{}\"", name.replace('"', "\\\""))
    }
}

fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first == '_' || first.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}
